# CircleCI configuration file
# https://circleci.com/docs/2.0/language-android
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    working_directory: ~/AndroidBaseAppKotlinMvvm
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx2048m
      GRADLE_OPTS: -Dorg.gradle.parallel=true -Dorg.gradle.caching=true -Dorg.gradle.configureondemand=true -Dkotlin.compiler.execution.strategy=in-process
    steps:
      - checkout
      - run: echo "movie.api.key=$MOVIE_API_KEY" >> local.properties
      - run: echo "signing.key.alias=$SIGNING_KEY_ALIAS" >> local.properties
      - run: echo "signing.key.password=$SIGNING_KEY_PASSWORD" >> local.properties
      - run: echo "signing.store.file=$SIGNING_STORE_FILE" >> local.properties
      - run: echo "signing.store.password=$SIGNING_STORE_PASSWORD" >> local.properties
      - restore_cache:
          key: gradle-{{ checksum "build.gradle.kts" }}
      - run:
          name: Run Detekt
          command: ./gradlew --stacktrace detekt
      - run:
          name: Run Ktlint
          command: ./gradlew ktlint
      - run:
          name: Run Lint
          command: ./gradlew lintDevDebug
      - run:
          name: Run Spotless
          command: ./gradlew spotlessKotlinCheck
      - run:
          name: Run Unit Tests
          command: ./gradlew testDevDebugUnitTest
      - run:
          name: Run UI Tests
          command: ./gradlew connectedDevDebugAndroidTest
      - run:
          name: Generate Code Coverage
          command: ./gradlew combinedTestReportDevDebug
      - run:
          name: Generate Dependency Updates
          command: ./gradlew dependencyUpdates -Drevision=release
      - store_artifacts:
          path: build/dependencyUpdates
      - codecov/upload:
          flags: unittest
          conf: .codecov/config.yml
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
