# Workflow name
name: Android CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Where will they run
jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up our JDK environment
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Write properties
      env:
        MOVIE_API_KEY: ${{ secrets.MOVIE_API_KEY }}
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        SIGNING_STORE_FILE: ${{ secrets.SIGNING_STORE_FILE }}
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      run: |
        echo "movie.api.key=$MOVIE_API_KEY" >> local.properties
        echo "signing.key.alias=$SIGNING_KEY_ALIAS" >> local.properties
        echo "signing.key.password=$SIGNING_KEY_PASSWORD" >> local.properties
        echo "signing.store.file=$SIGNING_STORE_FILE" >> local.properties
        echo "signing.store.password=$SIGNING_STORE_PASSWORD" >> local.properties

    - name: Run Detekt
      run: ./gradlew detekt

    - name: Run Kotlin Lint
      run: ./gradlew ktlint

    - name: Run Android Lint
      run: ./gradlew lintDevDebug

    - name: Run Spotless
      run: ./gradlew spotlessKotlinCheck

    - name: Run Unit Tests
      run: ./gradlew testDevDebugUnitTest

    - name: Run Instrumented tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew connectedDevDebugAndroidTest

    - name: Run Clean
      run: ./gradlew clean

    - name: Run Test Report
      run: ./gradlew combinedTestReportDevDebug

    - name: Run CodeCov
      uses: codecov/codecov-action@v1
