# Workflow name
name: Android CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Where will they run
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up our JDK environment
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Run Detekt
      run: ./gradlew detekt

    - name: Run Kotlin Lint
      run: ./gradlew ktlint

    - name: Run Android Lint
      run: ./gradlew lintDevDebug

    - name: Run Spotless
      run: ./gradlew spotlessKotlinCheck

    - name: Run Unit Tests
      run: ./gradlew testDevDebugUnitTest

    - name: Run Instrumented tests
      run: ./gradlew connectedDevDebugAndroidTest

    - name: Run Clean
      run: ./gradlew clean

    - name: Run Test Report
      run: ./gradlew combinedTestReportDevDebug

    - name: Run CodeCov
      uses: codecov/codecov-action@v1
